config/routes.rb
Hircle2::Application.routes.draw do
  resources :statuses

  devise_for :users
  resources :tasks
  resources :sub_tasks do
    post "add_member" => "sub_tasks#add_member", :as => "add_member"
    delete "delete_member" => "sub_tasks#delete_member", :as => "delete_member"
  end
  resources :comments

   root :to => 'home#index'

end

app/views/shared/_comments.html.erb
<table width="100%">
  <% comments.each do |comment| %>
      <tr>
        <td width="20%" style="text-align: right">
          <%= image_tag comment.user.avatar.url(:thumb) if comment.user %>
        </td>
        <td width="80%">
          <span class="commenter"><%= comment.user.email if comment.user.present? %></span>
          <span class="commented_at"><%= time_ago_in_words(comment.created_at) %>  ago</span>
        </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td class="comment_desc"><%= comment.description %></td>
      </tr>
  <% end %>
</table>

app/views/shared/_modal.html.erb
<div class="modal" id="hircle_modal" style="display: none;">
 <p>Loading...</p>
</div>

app/views/shared/_sub_task_panel.html.erb
<div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>

  <h3 id="modal_header"><%= sub_task.title %></h3>
  <input type="hidden" id="task_id_modal" value="<%= sub_task.task.id %>">
</div>
<div class="modal-body">
  <p id="modal-content">
    <%= best_in_place sub_task, :description, :type => :input, :nil => 'Enter Description' %>
  </p>

  <p id="priorities">
    <%= best_in_place sub_task, :priority_id, :type => :select, :collection => Priority.all.collect{|priority| [priority.id, priority.title]} %>
  </p>

  <p id="comments">
    <%= form_for Comment.new, :url => comments_url, :html => {:method => :post} do |f| %>
        <%= f.text_area :description, :style => "width: 90%;height: 60px;", :class => 'comment_description' %>
        <%= hidden_field :comment, :sub_task_id, :value => sub_task.id %>
    <% end %>
    <div style="width: 100%" class="sub_task_comments">
      <%= render :partial => 'shared/comments', :locals => {:comments => sub_task.comments }%>
    </div>
  </p>
</div>
<div class="modal-footer">

</div>

app/views/shared/_task_modal.html.erb
<div class="modal" id="hircle_task_modal" style="display: none;">

</div>